# -*- coding: utf-8 -*-
"""fastAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvaguBVj9U3Q8Y50StttsknfQS31kNsH
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import pickle
import pandas as pd

# Load model
with open("obesity_model.pkl", "rb") as f:
    model = pickle.load(f)

app = FastAPI()

# CORS settings
official_origins = [
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:8501",
    # Untuk development, bisa gunakan "*" (hati-hati di production)
    "*"
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=official_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ObesityInput(BaseModel):
    Gender: str
    Age: float
    Height: float
    Weight: float
    family_history_with_overweight: str
    FAVC: str
    FCVC: float
    NCP: float
    CAEC: str
    SMOKE: str
    CH2O: float
    SCC: str
    FAF: float
    TUE: float
    CALC: str
    MTRANS: str

@app.post("/predict")
def predict(data: ObesityInput):
    df = pd.DataFrame([data.dict()])
    prediction = model.predict(df)
    return {"prediction": prediction[0]}
